(in-package :pong-game)

(defun entrada ()
  (let ((x1 (jogador-x j1))
        (x2 (jogador-x j2)))
    (if (is-key-down :key-left)
      (setf (jogador-x j1) (- x1 10)))
    (if (is-key-down :key-right)
      (setf (jogador-x j1) (+ x1 10)))
    (if (is-key-down :key-a) 
      (setf (jogador-x j2) (- x2 10)))
    (if (is-key-down :key-d)
      (setf (jogador-x j2) (+ x2 10))))
  
  (let ((x1 (jogador-x j1))
        (x2 (jogador-x j2)))
    (if (>= x1 700)
      (setf (jogador-x j1) 700))
    (if (<= x1 0)
      (setf (jogador-x j1) 0))
    (if (>= x2 700)
      (setf (jogador-x j2) 700))
    (if (<= x2 0)
      (setf (jogador-x j2) 0))))

